# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNjO0n8fPxOy1itqlD2aAVJn9vT4Ri5z
"""

import streamlit as st
import numpy as np
import cv2
import tensorflow as tf
from streamlit_webrtc import webrtc_streamer, VideoTransformerBase
import os

# --- PAGE CONFIG ---
st.set_page_config(page_title="Live Handwriting Style Analyzer", layout="wide")

# --- LOAD MODEL ---
@st.cache_resource
def load_dyslexia_model():
    model_path = "Improved_Hybrid_AgeModel.keras"
    if os.path.exists(model_path):
        return tf.keras.models.load_model(model_path)
    return None

model = load_dyslexia_model()

class HandwritingAnalyzer(VideoTransformerBase):
    def __init__(self, age):
        self.age = age

    def transform(self, frame):
        img = frame.to_ndarray(format="bgr24")

        # Preprocess frame for the model
        img_resized = cv2.resize(img, (160, 160))
        img_normalized = img_resized / 255.0
        img_input = np.expand_dims(img_normalized, axis=0)

        # Age input
        age_input = np.array([[self.age]])

        # Predict
        if model:
            prob = model.predict([img_input, age_input], verbose=0)[0][0]

            # Determine Logic
            if prob < 0.50:
                label = f"Normal (Risk: {round(prob*100, 1)}%)"
                color = (0, 255, 0) # Green
            else:
                label = f"Dyslexic (Risk: {round(prob*100, 1)}%)"
                color = (0, 0, 255) # Red

            # Overlay result on the video stream
            cv2.putText(img, label, (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, color, 2)

        return img

# --- UI INTERFACE ---
st.title("📹 Live Handwriting Pattern Analysis")
st.markdown("""
This tool analyzes the **motion and formation** of letters in real-time.
Position the child's paper clearly within the camera frame.
""")

col1, col2 = st.columns([1, 3])

with col1:
    st.header("Settings")
    child_age = st.slider("Child's Age", 5, 15, 8)
    st.info("The BiLSTM layer analyzes the sequence of frames to detect erratic stroke patterns.")

with col2:
    if model:
        webrtc_streamer(
            key="handwriting-analysis",
            video_transformer_factory=lambda: HandwritingAnalyzer(child_age),
            rtc_configuration={"iceServers": [{"urls": ["stun:stun.l.google.com:19302"]}]}
        )
    else:
        st.error("Model file not found. Please ensure 'Improved_Hybrid_AgeModel.keras' is in the repository.")
